name: smart_translate_lints
description: Smart Translate Lints is a custom linting plugin for Flutter that helps catch missing translation strings in your code.
version: 1.0.2
homepage: https://github.com/smarthost-tr
repository: https://github.com/smarthost-tr/smart_translate_lints
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

# Include your custom lint as a dependency (replace with the actual package name)
# dependency_overrides:
#   smart_translate_lints: ^1.0.0

